name: 'acm serviceType on for Linux Agent'
description: 'Runs the acm serviceType on command using Ubuntu-latest agent.'
inputs:
  system_name:
    description: Custom input parameter
    required: true
  service_type:
    description: Custom input parameter
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      name: Run serviceType on
      env:
        system_name: ${{ inputs.system_name }}
        service_type: ${{ inputs.service_type }}
      run: |
        PATH=$PATH:/home/runner/acmhome/;export PATH
        cd /home/runner/testdir
        echo ".................about to run e2e test"
        acm serviceType on systemName=$system_name serviceType=$service_type
