name: 'acm platform on for Linux Agent'
description: 'Runs the acm platform on command in Ubuntu-latest agent.'
runs:
  using: "composite"
  steps:
      - shell: bash
        name: Run platform on
        run: |
          PATH=$PATH:/home/runner/acmhome/;export PATH
          cd /home/runner/testdir
          echo ".................about to run e2e test"
          acm platform on
