name: 'acm services on for Linux Agent'
description: 'Runs the acm services on command using Ubuntu-latest agent.'
inputs:
  system_name:
    description: Custom input parameter
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      name: Run services on
      env:
        system_name: ${{ inputs.system_name }}
      run: |
        PATH=$PATH:/home/runner/acmhome/;export PATH
        cd /home/runner/testdir
        echo ".................about to run e2e test"
        acm services on systemName=$system_name
