name: 'acm serviceType on for Linux Agent'
description: 'Runs the acm serviceType on command using Ubuntu-latest agent.'
inputs:
  system_name:
    description: Custom input parameter
    required: true
  service_type:
    description: Custom input parameter
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      name: Run serviceType off
      run: |
        PATH=$PATH:/home/runner/acmhome/;export PATH
        cd /home/runner/testdir
        echo ".................about to run e2e test"
        acm serviceType off systemName=$system_name serviceType=$service_type
