name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash          
    - shell: bash
      name: Configure agent
      env:
        ACM_SECRET: ${{ secrets.ACM_REPO }}
        ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
      run: |
        az extension add --name resource-graph
        echo "Current working directory is: "
        pwd
        mkdir /home/runner/keys
        mkdir /home/runner/keys/starter
        mkdir /home/runner/acmconfig/
        echo "$ACM_SECRET" > /home/runner/acmconfig/keys.yaml
        sudo mkdir /var/log/acm
        sudo chown -R runner:runner /var/log/acm
        sudo mkdir /opt/acm
        sudo chown -R runner:runner /opt/acm
        sudo mkdir /usr/acm
        sudo mkdir /usr/acm/keys
        sudo mkdir /usr/acm/keys/adminAccounts
        sudo chown -R runner:runner /usr/acm
        echo "$ACM_SECOND" > /usr/acm/keys/adminAccounts/keys.yaml
        sudo chown -R runner:runner /usr/acm
        echo 'new------------------'
        git --version
        sudo apt install -y dos2unix
        ## Install Terraform
        cd /home/runner
        mkdir terraform-download
        cd terraform-download
        wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
        unzip terraform_0.12.24_linux_amd64.zip
        #Move the terraform binary into a folder that is listed as part of the PATH variable.  
        mv terraform /usr/local/bin/
        echo 'and---------------------------------'
        cd /home/runner
        sudo apt -y install ansible
        aws --version
        pip3 install requests
        pip3 install pyyaml
        pip3 install IPy
        python3 --version
        python --version
        #Cause the ansible configuration to be owned by the agent user so that pipelines can change things like hosts file, etc.  
        sudo chown -R runner:runner /opt/pipx_bin/ansible
        echo 'then--------------------------------'
        sudo apt update && sudo apt upgrade
        sudo apt clean

############################################################################################
#    - run: goodbye.sh
#      shell: bash