#Manually enter the values for the input variables here, then a script will import these.
--- 
azdoConnection: 
  clientId: 
  clientSecret: 
agents:
  adminUser: 
  adminPwd: 
  pathToCloudInitScript: 
awsBackendTF: 
  awsPublicAccessKey: 
  awsSecretAccessKey: 
  s3BucketNameTF: 
  s3BucketRegionTF: 
  dynamoDbTableNameTF: 
  moduleKey: 
