#Manually enter the values for the input variables here, and then run a script to import them into the relevant tfvars files
--- 
meta: 
  subscriptionId: 
  tenantId: 
  pipeAzureRegion: 
azdoConnection: 
  clientId: 
  clientSecret: 
awsBackendTF: 
  - name: demo
    awsPublicAccessKey: 
    awsSecretAccessKey: 
    s3BucketNameTF: 
    s3BucketRegionTF: 
    dynamoDbTableNameTF: 
    moduleKey: 
