name: 'acm services off for Windows Agent'
description: 'Runs the acm services off command using Windows-latest agent.'
inputs:
  system_name:
    description: Custom input parameter
    required: true
runs:
  using: "composite"
  steps:
    - name: Run services off
      shell: pwsh
      env:
        system_name: ${{ inputs.system_name }}
      run: |
        $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
        cd C:\\stgng\\
        echo ".................about to run e2e test"
        acm services off systemName=$env:system_name
