## Copyright 2021 Green River IT (GreenRiverIT.com) as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/AgileCloudInstitute?tab=repositories    

cloud: aws
admin:
  instanceName: netadmin
  templateName: terraform-aws-building-blocks/iam-network-admin
  tool: terraform
tags:
  networkName: name-of-vpc
  systemName: name-of-system
  environmentName: name-of-environment
  ownerName: name-of-owner
networkFoundation:
  instanceName: demo
  templateName: terraform-aws-building-blocks/network-foundation
  tool: terraform
  region: us-west-2
imageBuilds:
  subnetForBuilds:
    instanceName: packer-demo
    templateName: terraform-aws-building-blocks/snet-packer
    tool: terraform
    cidrSubnet: 10.0.16.0/20
    cidrBlocks: admin
  images:
    - instanceName: aws-ebs-bkd
      templateName: packer-aws-building-blocks/aws-ebs-bkd
      tool: packer
      image_architecture: x86_64
      image_name: amzn2-ami-hvm*
      image_owner: amazon
      _instance_type: t2.micro
      _ssh_username: ec2-user
      _associate_public_ip_address: true
      _ssh_interface: public_ip
      provisioner_type: shell
      provisioner_script: packer-aws-building-blocks/aws-ebs-bkd.sh
systems:
  subnetsWithAutoScaling:
    - instanceName: demo
      templateName: terraform-aws-building-blocks/snet-autoscale
      cidrSubnet: 10.0.0.0/20
      image_name: packer_AWS*
      image_architecture: x86_64
      vmUserName: some-user
      vmPwd: abc-some-pwd-123
      placementStrategy: spread
  securityGroupRules:
    - instanceName: httpPublic
      templateName: terraform-aws-building-blocks/sg-rule
      type: ingress
      fromPort: 4000
      toPort: 4000
      cidrBlocks: public
  blobStorage:
    - instanceName: <your-storage-name>
      templateName: terraform-aws-building-blocks/s3