## Copyright 2021 Green River IT (GreenRiverIT.com) as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/AgileCloudInstitute?tab=repositories    

cloud: azure
source:
  - instanceName: azure-building-blocks
    repo: https://github.com/AgileCloudInstitute/azure-building-blocks.git
    branch: dev
  - instanceName: aws-building-blocks
    repo: https://github.com/AgileCloudInstitute/aws-building-blocks.git
    branch: dev
tags:
  networkName: name-of-vnet
  systemName: name-of-system
  environmentName: name-of-environment
  ownerName: name-of-owner
networkFoundation:
  instanceName: demo
  templateName: azure-building-blocks/terraform/net-found-tfbknd-az
  tool: terraform
  resourceGroupName: terraform-backend
  resourceGroupRegion: westus
systems:
  tfBackend:
    - instanceName: azProjMgtDemoTfBackend
      templateName: azure-building-blocks/az-cli/storage-tfbknd-az
      type: azurerm
      tool: az-cli
      keyVaultName: ProjectManagementBackend
      keyName: azProjMgtDemoTfBackendKey
      storageAccountName: tfbkendabc1234x
      environment: Dev
releaseDefinition:
  releaseDefinitions:
    - instanceName: ACM_DemoRelease
      projectName: ACM_ExampleProject
      vaultName: agentsVault
      YamlDefinitionFileName: ACM_DemoRelease.yaml
      repositories:
        - instanceName: ACM_ExampleCode