## Copyright 2021 Green River IT (GreenRiverIT.com) as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/AgileCloudInstitute?tab=repositories    

cloud: azure
organization: myOrg
source:
  - instanceName: azure-building-blocks
    repo: https://github.com/AgileCloudInstitute/azure-building-blocks.git
    branch: dev
  - instanceName: aws-building-blocks
    repo: https://github.com/AgileCloudInstitute/aws-building-blocks.git
    branch: dev
tags:
  networkName: name-of-vnet
  systemName: name-of-system
  environmentName: name-of-environment
  ownerName: name-of-owner
networkFoundation:
  instanceName: admin
  templateName: azure-building-blocks/terraform/foundationAdmin
  tool: terraform
  resourceGroupName: admin
  resourceGroupRegion: westus
systems:
  admin:
    - instanceName: tfBackend
      templateName: azure-building-blocks/terraform/ad-admin
      tool: terraform
    - instanceName: pipelineAgents
      templateName: azure-building-blocks/terraform/ad-admin
      tool: terraform
#    - instanceName: projectManagement
#      templateName: azure-building-blocks/terraform/ad-admin
#      tool: terraform
#    - instanceName: releaseManagement
#      templateName: azure-building-blocks/terraform/ad-admin
#      tool: terraform