## Copyright 2021 Green River IT (GreenRiverIT.com) as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/AgileCloudInstitute?tab=repositories    

cloud: azure
tags:
  networkName: name-of-vnet
  systemName: name-of-system
  environmentName: name-of-environment
  ownerName: name-of-owner
networkFoundation:
  instanceName: demo
  templateName: azure-building-blocks/terraform/network-foundation
  tool: terraform
  resourceGroupName: azdo-agents
  resourceGroupRegion: westus
imageBuilds:
  subnetForBuilds:
    instanceName: packer-demo
    templateName: azure-building-blocks/terraform/snet-packer
    tool: terraform
    cidrSubnet: 10.0.9.0/24
  images:
    - instanceName: RHEL73_AZDO_Agent
      templateName: azure-building-blocks/packer/rhel7-azure-arm-azdo-agent
      tool: packer
      ssh_user: packer
      ssh_pass: just-me-123
      init_script: \\config-outside-acm-path\\azure\\rhel7-startup-azdo-agent.sh
systems:
  subnetsWithScaleSet:
    - instanceName: azdoAgents
      templateName: azure-building-blocks/terraform/snet-agents
      tool: terraform
      imageName: RHEL73_AZDO_Agent
      cidrSubnet: 10.0.6.0/24
      vmUserName: azureuser
      vmPwd: abc-some-pwd-123
      vaultName: agentsVault
      cloudInit: \\config-outside-acm-path\\azure\\startup-script-demo.sh
#--projectManagement:
#--  projects:
#--    - instanceName: SampleProject
#--      templateName: azure-building-blocks/terraform/azdo-project
#--      tool: terraform
#--      code:
#--        - instanceName: SampleCode
#--          templateName: azure-building-blocks/terraform/azdo-code
#--          tool: terraform
#--          sourceRepo: https://github.com/AgileCloudInstitute/aws-building-blocks.git
#--          buildName: SampleCode
#--          endpointTemplate: azure-building-blocks/api/azdo-service-conn-other-git.json
#--releaseDefinition:
#--  releaseDefinitions:
#--    - instanceName: SampleRelease
#--      projectName: SampleProject
#--      vaultName: agentsVault
#--      YamlDefinitionFileName: CICD_TerraformAWS_IaC.yaml
#--      repositories:
#--        - instanceName: SampleCode
#-->        - instanceName: terraform-aws-starter-kit
#>    - instanceName: createStorageAccountAzure.yaml
#>      projectName: SampleProject
#>      YamlDefinitionFileName: createStorageAccountAzure.yaml
#>      repositories:
#>        - instanceName: azure-storage-account-toolkit
#>    - instanceName: destroyStorageAccountAzure
#>      projectName: SampleProject
#>      YamlDefinitionFileName: destroyStorageAccountAzure.yaml
#>      repositories:
#>        - instanceName: azure-storage-account-toolkit