## Copyright 2021 Green River IT (GreenRiverIT.com) as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/AgileCloudInstitute?tab=repositories    

dependencies:
  - name: azure-cli
    version: "2.17"
    download-link-windows: 
    download-link-linux:
    modules:
    - name: azure-cli-ext-azure-devops
      version: "0.18"
  - name: git
    version: "2.27"
    download-link-windows: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.27.0.tar.gz
    download-link-linux:
    checksums: 
      - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.27.0.tar.sign
      - url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.27.0.tar.xz
  - name: terraform
    version: "0.14"
    download-link-windows: https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_windows_amd64.zip
    download-link-linux: https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip
    checksums:
      - url: https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_SHA256SUMS
      - url: https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_SHA256SUMS.348FFC4C.sig
      - url: https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_SHA256SUMS.72D7468F.sig
      - url: https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_SHA256SUMS.sig
  - name: packer
    version: "1.7"
    download-link-windows: https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_windows_amd64.zip
    download-link-linux: https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip
    checksums: 
      - url: https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_SHA256SUMS
      - url: https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_SHA256SUMS.sig