name: 'Compile Windows App'
description: 'Compiles app for windows.'
runs:
  using: "composite"
  steps:
    - name: Compile App
      shell: pwsh
      run: |
        echo "About to start"
        python -m pip install --upgrade pip PyYaml
        python -m pip install --upgrade pip pyinstaller
        echo "About to: pyinstaller acm.py"
        pyinstaller acm.py
        New-Item -ItemType Directory -Force -Path C:\\Users\\runneradmin\\acmhome\\
        move dist\\acm\\ C:\\Users\\runneradmin\\acmhome\\
        echo "About to dir C:\\Users\\runneradmin\\acmhome\\"
        dir C:\\Users\\runneradmin\\acmhome\\
