name: 'Compile Windows App'
description: 'Compiles app for windows.'
runs:
  using: "composite"
  steps:
    - name: Compile App
      shell: pwsh
      run: |
        python -m pip install --upgrade pip PyYaml
        python -m pip install --upgrade pip pyinstaller
        python -m pip install --upgrade charset-normalizer
        New-Item -ItemType Directory -Force -Path C:\\Users\\runneradmin\\acmhome\\
        echo "About to start"
        cd app
        del __init__.py
        echo "About to: pyinstaller acm.py"
        pyinstaller acm.py
        Move-Item -Path "dist\\acm\\*" -Destination "C:\\Users\\runneradmin\\acmhome\\"
        echo "About to dir C:\\Users\\runneradmin\\acmhome\\"
        cd C:\\Users\\runneradmin\\acmhome\\
        dir 
    - name: One Show contents
      shell: pwsh
      run: |
        echo "About to dir C:\\Users\\runneradmin\\acmhome\\"
        cd C:\\Users\\runneradmin\\acmhome\\
        dir
