name: 'Compile Windows App'
description: 'Compiles app for windows.'
runs:
  using: "composite"
  steps:
    - name: Compile App
      shell: pwsh
      run: |
        echo "About to start"
        python -m pip install --upgrade pip PyYaml
        python -m pip install --upgrade pip pyinstaller
        echo "About to: pyinstaller myapp.py"
        pyinstaller myapp.py
        New-Item -ItemType Directory -Force -Path C:\\Users\\runneradmin\\myapphome\\
        move dist\\myapp\\ C:\\Users\\runneradmin\\myapphome\\
        echo "About to dir C:\\Users\\runneradmin\\myapphome\\"
        dir C:\\Users\\runneradmin\\myapphome\\
