name: dev-environ
on:
  push:
    branches:
      - dev
jobs: 
  push-to-test-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.HUSH }}
      - shell: bash
        name: Push changes to test branch
        run: |
          git config --global user.email "Agile.Cloud.Institute@GreenRiverIT.com"
          git config --global user.name "AgileCloudInstitute"
          git init
          git remote set-url origin "https://github.com/${GITHUB_REPOSITORY}.git"
          git branch -M test
          git add --all
          git push --force -u origin test
          #git config --global user.email "Agile.Cloud.Institute@GreenRiverIT.com"
          #git config --global user.name "AgileCloudInstitute"
          #git init
          #git remote set-url origin "https://github.com/${GITHUB_REPOSITORY}.git"
          #git branch -M test
          #git add --all
          #git push --force -u origin test

#  push-to-test-branch:
#    needs: [unit-tests-linux-misc, unit-tests-linux-cloudformation, unit-tests-linux-terraform-packer, unit-tests-linux-arm-template, unit-tests-windows-misc, unit-tests-windows-cloudformation, unit-tests-windows-terraform-packer, unit-tests-windows-arm-template]
