name: dev-environ
on:
  push:
    branches:
      - dev
jobs: 
  call-e2e-tests-custom-api-workflow:
    uses: ./.github/workflows/custom-api.yml
    secrets: inherit
#  call-e2e-tests-workflow:
#    uses: ./.github/workflows/e2e-tests.yml
#    secrets: inherit
 