name: dev-environ
on:
  push:
    branches:
      - dev
jobs: 
  call-e2e-tests-workflow:
    uses: .github/workflows/e2e-tests.yml
    secrets:
      ACM_REPO_ZERO: ${{ secrets.ACM_REPO_ZERO }}
      ACM_CONFIG_ZERO: ${{ secrets.ACM_REPO_ZERO }}
#  push-to-test-branch:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          token: ${{ secrets.HUSH }}
#      - shell: bash
#        name: Push changes to test branch
#        env:
#          GH_USER_NAME: ${{ secrets.GH_USER_NAME }}
#          GH_USER_EMAIL: ${{ secrets.GH_USER_EMAIL }}
#        run: |
#          git config --global user.email "$GH_USER_EMAIL"
#          git config --global user.name "$GH_USER_NAME"
#          git init
#          git remote set-url origin "https://github.com/${GITHUB_REPOSITORY}.git"
#          git branch -M test
#          git add --all
#          git push --force -u origin test
 