name: dev-environ
on:
  push:
    branches:
      - dev
jobs:
  unit-tests-linux-misc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureUbuntuAgent
        uses: ./.github/actions/ubuntu-provisioner
      - name: Put secrets in file
        shell: bash
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: | 
          echo "$ACM_SECRET" > /home/runner/acmconfig/keys.yaml
          echo "$ACM_SECOND" > /usr/acm/keys/adminAccounts/keys.yaml
      - shell: bash
        name: Run setup on
        run: |
          cd /home/runner/work/AgileCloudManager/
          python AgileCloudManager/app/acm.py setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-projects-cf.git
      - shell: bash
        name: Run test_command_builder
        run: |
          cd /home/runner/work/AgileCloudManager/
          python -m unittest AgileCloudManager.unitTests.test_command_builder
      - shell: bash
        name: Run test_workflow_and_changes
        run: |
          cd /home/runner/work/AgileCloudManager/
          python -m unittest AgileCloudManager.unitTests.test_workflow_and_changes
      - shell: bash
        name: Run test_controller_custom.py
        run: |
          cd /home/runner/work/AgileCloudManager/
          python -m unittest AgileCloudManager.unitTests.test_controller_custom
      - shell: bash
        name: Delete Secrets
        run: |
          rm /home/runner/acmconfig/keys.yaml
  unit-tests-linux-cloudformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureUbuntuAgent
        uses: ./.github/actions/ubuntu-provisioner
      - name: Put secrets in file
        shell: bash
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: | 
          echo "$ACM_SECRET" > /home/runner/acmconfig/keys.yaml
          echo "$ACM_SECOND" > /usr/acm/keys/adminAccounts/keys.yaml
      - shell: bash
        name: Run setup on
        run: |
          cd /home/runner/work/AgileCloudManager/
          python AgileCloudManager/app/acm.py setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-projects-cf.git
      - shell: bash
        name: Run test_controller_cf
        run: |
          cd /home/runner/work/AgileCloudManager/
          python -m unittest AgileCloudManager.unitTests.test_controller_cf
      - shell: bash
        name: Delete Secrets
        run: |
          rm /home/runner/acmconfig/keys.yaml
  unit-tests-linux-terraform-packer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureUbuntuAgent
        uses: ./.github/actions/ubuntu-provisioner
      - name: Put secrets in file
        shell: bash
        env:
         ACM_SECRET: ${{ secrets.ACM_REPO }}
         ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: | 
          echo "$ACM_SECRET" > /home/runner/acmconfig/keys.yaml
          echo "$ACM_SECOND" > /usr/acm/keys/adminAccounts/keys.yaml
      - shell: bash
        name: Run setup on
        run: |
          cd /home/runner/work/AgileCloudManager/
          python AgileCloudManager/app/acm.py setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-projects-cf.git
      - shell: bash
        name: Run test_controller_terraform_and_packer_one
        run: |
          cd /home/runner/work/AgileCloudManager/
          python -m unittest AgileCloudManager.unitTests.test_controller_terraform_and_packer_one
      - shell: bash
        name: Run test_controller_terraform_and_packer_two
        run: |
          cd /home/runner/work/AgileCloudManager/
          python -m unittest AgileCloudManager.unitTests.test_controller_terraform_and_packer_two
      - shell: bash
        name: Delete Secrets
        run: |
          rm /home/runner/acmconfig/keys.yaml
  unit-tests-linux-arm-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureUbuntuAgent
        uses: ./.github/actions/ubuntu-provisioner
      - name: Put secrets in file
        shell: bash
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: | 
          echo "$ACM_SECRET" > /home/runner/acmconfig/keys.yaml
          echo "$ACM_SECOND" > /usr/acm/keys/adminAccounts/keys.yaml
      - shell: bash
        name: Run setup on
        run: |
          cd /home/runner/work/AgileCloudManager/
          python AgileCloudManager/app/acm.py setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-projects-cf.git
      - shell: bash
        name: Run test_controller_arm
        run: |
          cd /home/runner/work/AgileCloudManager/
          python -m unittest AgileCloudManager.unitTests.test_controller_arm
      - shell: bash
        name: Delete Secrets
        run: |
          rm /home/runner/acmconfig/keys.yaml
  unit-tests-windows-misc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureWindowsAgent 
        uses: ./.github/actions/windows-provisioner
      - shell: pwsh
        name: Run setup on
        run: |
          echo 'Contents are: --------------------------------------------------'
          dir
          echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
          cd D:\\a\\AgileCloudManager\\
          echo 'Contents are: --------------------------------------------------'
          dir
          python AgileCloudManager\\app\\acm.py setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-projects-cf.git
          dir
      - shell: pwsh
        name: Run test_command_builder
        run: |
          echo "................about to list contents"
          dir
          echo "................about to cd D:\\a\\AgileCloudManager\\ "
          cd D:\\a\\AgileCloudManager\\
          echo 'Contents are: --------------------------------------------------'
          dir
          echo ".................about to run unit test"
          python -m unittest AgileCloudManager.unitTests.test_command_builder
      - shell: pwsh
        name: Run test_workflow_and_changes
        run: |
          echo "................about to list contents"
          dir
          echo "................about to cd D:\\a\\AgileCloudManager\\ "
          cd D:\\a\\AgileCloudManager\\
          echo 'Contents are: --------------------------------------------------'
          dir
          echo ".................about to run unit test"
          python -m unittest AgileCloudManager.unitTests.test_workflow_and_changes
      - shell: pwsh
        name: Run test_controller_custom.py
        run: |
          echo "................about to list contents"
          dir
          echo "................about to cd D:\\a\\AgileCloudManager\\ "
          cd D:\\a\\AgileCloudManager\\
          echo 'Contents are: --------------------------------------------------'
          dir
          echo ".................about to run unit test"
          python -m unittest AgileCloudManager.unitTests.test_controller_custom
      - name: Delete Secrets
        run: |
          del "C:\\Users\\runneradmin\\acmconfig\\keys.yaml"
          del 'C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml'
  unit-tests-windows-cloudformation:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureWindowsAgent 
        uses: ./.github/actions/windows-provisioner
      - shell: pwsh
        name: Run setup on
        run: |
          echo 'Contents are: --------------------------------------------------'
          dir
          echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
          cd D:\\a\\AgileCloudManager\\
          echo 'Contents are: --------------------------------------------------'
          dir
          python AgileCloudManager/app/acm.py setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-projects-cf.git
          dir
      - shell: pwsh
        name: Run test_controller_cf
        run: |
          echo "................about to list contents"
          dir
          echo "................about to cd D:\\a\\AgileCloudManager\\ "
          cd D:\\a\\AgileCloudManager\\
          echo 'Contents are: --------------------------------------------------'
          dir
          echo ".................about to run unit test"
          python -m unittest AgileCloudManager.unitTests.test_controller_cf
      - name: Delete Secrets
        run: |
          del "C:\\Users\\runneradmin\\acmconfig\\keys.yaml"
          del 'C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml'
  unit-tests-windows-terraform-packer:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureWindowsAgent 
        uses: ./.github/actions/windows-provisioner
      - shell: pwsh
        name: Run setup on
        run: |
          echo 'Contents are: --------------------------------------------------'
          dir
          echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
          cd D:\\a\\AgileCloudManager\\
          echo 'Contents are: --------------------------------------------------'
          dir
          python AgileCloudManager/app/acm.py setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-projects-cf.git
          dir
      - shell: pwsh
        name: Run test_controller_terraform_and_packer_one
        run: |
          echo "................about to list contents"
          dir
          echo "................about to cd D:\\a\\AgileCloudManager\\ "
          cd D:\\a\\AgileCloudManager\\
          echo 'Contents are: --------------------------------------------------'
          dir
          echo ".................about to run unit test"
          python -m unittest AgileCloudManager.unitTests.test_controller_terraform_and_packer_one
      - shell: pwsh
        name: Run test_controller_terraform_and_packer_two
        run: |
          echo "................about to list contents"
          dir
          echo "................about to cd D:\\a\\AgileCloudManager\\ "
          cd D:\\a\\AgileCloudManager\\
          echo 'Contents are: --------------------------------------------------'
          dir
          echo ".................about to run unit test"
          python -m unittest AgileCloudManager.unitTests.test_controller_terraform_and_packer_two
      - name: Delete Secrets
        run: |
          del "C:\\Users\\runneradmin\\acmconfig\\keys.yaml"
          del 'C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml'
  unit-tests-windows-arm-template:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureWindowsAgent 
        uses: ./.github/actions/windows-provisioner
      - shell: pwsh
        name: Run setup on
        run: |
          echo 'Contents are: --------------------------------------------------'
          dir
          echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
          cd D:\\a\\AgileCloudManager\\
          echo 'Contents are: --------------------------------------------------'
          dir
          python AgileCloudManager/app/acm.py setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-projects-cf.git
          dir
      - shell: pwsh
        name: Run test_controller_arm
        run: |
          echo "................about to list contents"
          dir
          echo "................about to cd D:\\a\\AgileCloudManager\\ "
          cd D:\\a\\AgileCloudManager\\
          echo 'Contents are: --------------------------------------------------'
          dir
          echo ".................about to run unit test"
          python -m unittest AgileCloudManager.unitTests.test_controller_arm
      - name: Delete Secrets
        run: |
          del "C:\\Users\\runneradmin\\acmconfig\\keys.yaml"
          del 'C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml'
  push-to-test-branch:
    needs: [unit-tests-linux-misc, unit-tests-linux-cloudformation, unit-tests-linux-terraform-packer, unit-tests-linux-arm-template, unit-tests-windows-misc, unit-tests-windows-cloudformation, unit-tests-windows-terraform-packer, unit-tests-windows-arm-template]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.HUSH }}
      - shell: bash
        name: Push changes to test branch
        run: |
          git config --global user.email "Agile.Cloud.Institute@GreenRiverIT.com"
          git config --global user.name "AgileCloudInstitute"
          git init
          git remote set-url origin "https://github.com/${GITHUB_REPOSITORY}.git"
          git branch -M test
          git add --all
          git push --force -u origin test

#  push-to-test-branch:
#    needs: [unit-tests-linux-misc, unit-tests-linux-cloudformation, unit-tests-linux-terraform-packer, unit-tests-linux-arm-template]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - shell: bash
#        name: Push changes to test branch
#        env:
#          GIT_PAT: ${{ secrets.HUSH }}
#        run: |
#          repoWithToken="https://"$GIT_PAT"@github.com/AgileCloudInstitute/AgileCloudManager.git"
#          git config --global user.email "Agile.Cloud.Institute@GreenRiverIT.com"
#          git config --global user.name "AgileCloudInstitute"
#          git init
#          git remote set-url origin $repoWithToken
#          git branch -M test
#          git add --all
#          git push --force -u origin test
