name: dev-environ-tests-linux
on: [push]
jobs:
  push-to-test-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        name: Configure agent
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: |
          az extension add --name resource-graph
          echo "Current working directory is: "
          pwd
          ls -al
          mkdir /home/runner/acmconfig/
          echo "$ACM_SECRET" > /home/runner/acmconfig/keys.yaml
          sudo chown -R runner:runner /home/runner/acmconfig
          git init
          git add --all
          git commit -m "more upgrades"
          git branch -M test
          git push --force -u origin test