name: dev-environ-tests-linux
on: [push]
jobs:
  push-to-test-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        name: Configure agent
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
          GIT_PAT: ${{ secrets.HUSH }}
        run: |
          az extension add --name resource-graph
          echo "Current working directory is: "
          pwd
          ls -al
          mkdir /home/runner/acmconfig/
          echo "$ACM_SECRET" > /home/runner/acmconfig/keys.yaml
          sudo chown -R runner:runner /home/runner/acmconfig
          #repoWithToken="https://"$gitPass$repoPart2
          repoWithToken="https://"$GIT_PAT"@github.com/AgileCloudInstitute/AgileCloudManager.git"
          repoWithTokenAndName="https://AgileCloudInstitute:"$GIT_PAT"@github.com/AgileCloudInstitute/AgileCloudManager.git"
          git init
          git config --global url."$repoWithTokenAndName".insteadOf "https://github.com"
          git remote set-url origin $repoWithToken
          git add --all
          git commit -m "more upgrades"
          git branch -M test
          git push --force -u origin test