name: e2e-tests-windows
on:
  push:
    branches:
      - dev
jobs:
  e2e-tests-windows-arm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureWindowsAgent 
        uses: ./.github/actions/windows-provisioner
      - id: CompileAppForWindows
        uses: ./.github/actions/app-compiler-windows
      - shell: python
        name: Save secrets to file
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: |
          import base64, subprocess, sys, os, pathlib
          #Import first secrets file
          with open('C:\\Users\\runneradmin\\acmconfig\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECRET'])
          #Import second secrets file
          with open('C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECOND'])
      - name: Run setup on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo 'About to: acm setup on'
          acm setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-projects-arm.git
          echo "About to dir"
          dir
      - name: Run platform on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm platform on
      - name: Run platform off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm platform off
      - name: Setup Off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run setup off"
          acm setup off
          echo "About to dir"
          dir
      - name: Delete Secrets
        run: |
          del "C:\\Users\\runneradmin\\acmconfig\\keys.yaml"
          del 'C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml'
  e2e-tests-windows-cloudformation:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureWindowsAgent
        uses: ./.github/actions/windows-provisioner
      - id: CompileAppForWindows
        uses: ./.github/actions/app-compiler-windows
      - shell: python
        name: Save secrets to file
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: |
          import base64, subprocess, sys, os, pathlib
          #Import first secrets file
          with open('C:\\Users\\runneradmin\\acmconfig\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECRET'])
          #Import second secrets file
          with open('C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECOND'])
      - name: Run setup on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo 'About to: acm setup on'
          acm setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-projects-cf.git
          echo "About to dir"
          dir
      - name: Run platform on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd 'C:\\stgng\\'
          echo ".................about to run e2e test"
          acm platform on
      - name: Run platform off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm platform off
      - name: Setup Off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run setup off"
          acm setup off
          echo "About to dir"
          dir
      - name: Delete Secrets
        run: |
          del C:\\Users\\runneradmin\\acmconfig\\keys.yaml
          del C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml
  e2e-tests-windows-custom:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureWindowsAgent
        uses: ./.github/actions/windows-provisioner
      - id: CompileAppForWindows
        uses: ./.github/actions/app-compiler-windows
      - shell: python
        name: Save secrets to file
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: |
          import base64, subprocess, sys, os, pathlib
          #Import first secrets file
          with open('C:\\Users\\runneradmin\\acmconfig\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECRET'])
          #Import second secrets file
          with open('C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECOND'])
      - name: Run setup on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo 'About to: acm setup on'
          acm setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-custom.git
          echo "About to dir"
          dir
      - name: Run platform on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm platform on
      - name: Run platform off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm platform off
      - name: Setup Off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run setup off"
          acm setup off
          echo "About to dir"
          dir
      - name: Delete Secrets
        run: |
          del C:\\Users\\runneradmin\\acmconfig\\keys.yaml
          del C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml
  e2e-tests-windows-terraform-packer:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureWindowsAgent
        uses: ./.github/actions/windows-provisioner
      - id: CompileAppForWindows
        uses: ./.github/actions/app-compiler-windows
      - shell: python
        name: Save secrets to file
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: |
          import base64, subprocess, sys, os, pathlib
          #Import first secrets file
          with open('C:\\Users\\runneradmin\\acmconfig\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECRET'])
          #Import second secrets file
          with open('C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECOND'])
      - name: Run setup on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo 'About to: acm setup on'
          acm setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-terraform-packer.git
          echo "About to dir"
          dir
      - name: Run tfbackend serviceType on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm serviceType on systemName=tfbackend serviceType=tfBackend
      - name: Run tfbackend serviceType off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm serviceType off systemName=tfbackend serviceType=tfBackend
      - name: Run tfbackend serviceInstance on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm serviceInstance on systemName=tfbackend serviceType=tfBackend serviceInstance=adminAccounts
      - name: Run tfbackend serviceInstance off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm serviceInstance off systemName=tfbackend serviceType=tfBackend serviceInstance=adminAccounts
      - name: Run tfbackend services on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm services on systemName=tfbackend
      - name: Run admin foundation on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm foundation on systemName=admin
      - name: Run admin services on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm services on systemName=admin
      - name: Run agents foundation on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm foundation on systemName=agents
      - name: Run agents services on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm services on systemName=agents
      - name: Run agents services off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm services off systemName=agents
      - name: Run agents foundation off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm foundation off systemName=agents
      - name: Run admin services off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm services off systemName=admin
      - name: Run admin foundation off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm foundation off systemName=admin
      - name: Run tfbackend services off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm services off systemName=tfbackend
      - name: Setup Off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run setup off"
          acm setup off
          echo "About to dir"
          dir
      - name: Delete Secrets
        run: |
          del C:\\Users\\runneradmin\\acmconfig\\keys.yaml
          del C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml


#  push-to-test-branch:
#    needs: [e2e-tests-windows-arm, e2e-tests-windows-cloudformation, e2e-tests-windows-custom, e2e-tests-windows-terraform-packer ]
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3
#      - shell: python
#        name: Push changes to test branch
#        env:
#          GIT_PAT: ${{ secrets.HUSH }}
#        run: |
#          repoWithToken="https://"$GIT_PAT"@github.com/AgileCloudInstitute/AgileCloudManager.git"
#          git config --global user.email "Agile.Cloud.Institute@GreenRiverIT.com"
#          git config --global user.name "AgileCloudInstitute"
#          git init
#          git remote set-url origin $repoWithToken
#          git branch -M test
#          git add --all
#          git push --force -u origin test
