# https://docs.github.com/en/actions/examples
# check-bats-version
# learn-github-actions
name: org-secret-into-file
on: [push]
jobs:
  put-secret-into-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '14'
#      - run: npm install -g bats
#      - run: bats -v
      - run: echo ${{ secrets.EXAMPLE }}
      - run: echo ${{ secrets.HUSH }}
#      - run: ls -al
#      - run: ls -al ..
#      - run: ls -al ../..
#      - run: whoami
      - run: mkdir /home/runner/stuff
      - run: echo ${{ secrets.EXAMPLE }} > /home/runner/stuff/secrets.txt
      - run: echo ${{ secrets.HUSH }} > /home/runner/stuff/hush.txt
#      - run: ls -al /home/runner/stuff
      - run: cat /home/runner/stuff/secrets.txt
      - run: cat /home/runner/stuff/hush.txt