# https://docs.github.com/en/actions/examples
# check-bats-version
# learn-github-actions
name: org-secret-into-file
on: [push]
jobs:
  put-secret-into-file:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          ORG_SECRET: ${{ secrets.ACM_STARTER }}
        run: |
          echo "$ORG_SECRET"
          mkdir /home/runner/stuff
          echo "$ORG_SECRET" > /home/runner/stuff/secrets.txt
          cat /home/runner/stuff/secrets.txt
          rm -rf /home/runner/stuff