name: org-secret-into-file
on: [push]
jobs:
  put-secret-into-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
        run: |
          mkdir /home/runner/stuff
          echo "$ACM_SECRET" > /home/runner/stuff/acm.txt
          echo 'cat-----------------------------------'
          cat -n /home/runner/stuff/acm.txt
          sudo mkdir /var/log/acm
          sudo chown -R runner:runner /var/log/acm
          sudo mkdir /opt/acm
          sudo chown -R runner:runner /opt/acm
          sudo mkdir /usr/acm
          sudo chown -R runner:runner /usr/acm
          echo 'new------------------'
          git --version
          sudo apt install -y dos2unix
          ## Install Terraform
          cd /home/runner
          mkdir terraform-download
          cd terraform-download
          wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
          unzip terraform_0.12.24_linux_amd64.zip
          #Move the terraform binary into a folder that is listed as part of the PATH variable.  
          mv terraform /usr/local/bin/
          echo 'and---------------------------------'
          cd /home/runner
          apt install -y telnet
          apt -y install ansible
          apt install -y azure-cli