# https://docs.github.com/en/actions/examples
# check-bats-version
# learn-github-actions
name: org-secret-into-file
on: [push]
jobs:
  put-secret-into-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
        run: |
          mkdir /home/runner/stuff
          echo "$ACM_SECRET" > /home/runner/stuff/acm.txt
          echo 'cat-----------------------------------'
          cat -n /home/runner/stuff/acm.txt
          echo 'wc-----------------------------------'
          wc -w /home/runner/stuff/acm.txt
          echo 'var-----------------------------------'
          ls -al /var
          echo 'log-----------------------------------'
          ls -al /var/log
          echo 'opt-----------------------------------'
          ls -al /opt
          echo 'usr-----------------------------------'
          ls -al /usr

#    steps:
#      - uses: actions/checkout@v3
#      - shell: bash
#        env:
#          ORG_SECRET: ${{ secrets.ACM_STARTER }}
#          REPO_SECRET: ${{ secrets.HUSH }}
#        run: |
#          echo "$ORG_SECRET"
#          echo "$REPO_SECRET"
#          mkdir /home/runner/stuff
#          echo "$ORG_SECRET" > /home/runner/stuff/secrets.txt
#          echo "$REPO_SECRET" > /home/runner/stuff/hush.txt
#          cat /home/runner/stuff/secrets.txt
#          cat /home/runner/stuff/hush.txt
#          ls -al
