# https://docs.github.com/en/actions/examples
# check-bats-version
# learn-github-actions
name: org-secret-into-file
on: [push]
jobs:
  put-secret-into-file:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          ORG_SECRET: ${{ secrets.ACM_STARTER }}
          REPO_SECRET: ${{ secrets.HUSH }}
        run: |
          echo "$ORG_SECRET"
          echo "$REPO_SECRET"
          mkdir /home/runner/stuff
          echo "$ORG_SECRET" > /home/runner/stuff/secrets.txt
          echo "$REPO_SECRET" > /home/runner/stuff/hush.txt
          cat /home/runner/stuff/secrets.txt
          cat /home/runner/stuff/hush.txt

#    steps:
#      - uses: actions/checkout@v3
#      - run: echo ${{ secrets.EXAMPLE }}
#      - run: echo ${{ secrets.HUSH }}
#      - run: mkdir /home/runner/stuff
#      - run: echo ${{ secrets.EXAMPLE }} > /home/runner/stuff/secrets.txt
#      - run: echo ${{ secrets.HUSH }} > /home/runner/stuff/hush.txt
#      - run: cat /home/runner/stuff/secrets.txt
#      - run: cat /home/runner/stuff/hush.txt