name: org-secret-into-file
on: [push]
jobs:
  put-secret-into-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
        run: |
          mkdir /home/runner/stuff
          echo "$ACM_SECRET" > /home/runner/stuff/acm.txt
          echo 'cat-----------------------------------'
          cat -n /home/runner/stuff/acm.txt
          sudo mkdir /var/log/acm
          sudo chown -R runner:runner /var/log/acm
          sudo mkdir /opt/acm
          sudo chown -R runner:runner /opt/acm
          sudo mkdir /usr/acm
          sudo chown -R runner:runner /usr/acm
          echo 'new------------------'
          git --version