name: release-manually
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
      description:
        description: 'Description of release'
        required: true
        type: string
jobs:
  release-a-linux-version:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        name: Release
        env:
          DESCRIPTION: ${{ inputs.description }}
          VERSION: ${{ inputs.version }}
          GH_TOKEN: ${{ secrets.HUSH }}
        run: |
          vers="linux-"$VERSION
          echo "About to print version"
          echo $vers
          nameOfRelease="AgileCloudManager-"$vers
          echo "About to print name of release"
          echo $nameOfRelease 
          echo "About to create release"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/AgileCloudInstitute/AgileCloudManager/releases \
            -f tag_name=$vers \
            -f target_commitish='release-linux' \
            -f name=$nameOfRelease \
            -f body="$DESCRIPTION" \
            -F draft=false \
            -F prerelease=false \
            -F generate_release_notes=false 
  release-a-windows-version:
    runs-on: windows-latest
    steps:
      - shell: pwsh
        name: Release
        env:
          DESCRIPTION: ${{ inputs.description }}
          VERSION: ${{ inputs.version }}
          GH_TOKEN: ${{ secrets.HUSH }}
        run: |
          $vers="windows-"+$env:VERSION
          echo "About to print version"
          echo $vers
          $nameOfRelease="AgileCloudManager-"+$vers
          echo "About to print name of release"
          echo $nameOfRelease 
          echo "About to create release"
          gh api --method POST -H "Accept: application/vnd.github+json" /repos/AgileCloudInstitute/AgileCloudManager/releases -f tag_name=$vers -f target_commitish='release-windows' -f name=$nameOfRelease -f body="$env:DESCRIPTION" -F draft=false -F prerelease=false -F generate_release_notes=false 
  e2e-tests-windows-arm:
    needs: [release-a-windows-version]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureWindowsAgent 
        uses: ./.github/actions/windows-provisioner
      - shell: pwsh
        name: Download and extract Release
        env:
          DESCRIPTION: ${{ inputs.description }}
          VERSION: ${{ inputs.version }}
          GH_TOKEN: ${{ secrets.HUSH }}
        run: |
          $vers="windows-"+$env:VERSION
          $repoWithToken = '"https://"+$env:GH_TOKEN+"@github.com/AgileCloudInstitute/AgileCloudManager"'
          echo "About to download and extract release"
          mkdir staging
          gh release download $vers --archive tar.gz --repo $repoWithToken
          $folderName="AgileCloudManager-"+$vers
          $tarName=$folderName+".tar.gz"
          tar -xvf $tarName -C staging
          $stagingFolderName="staging\\"+$folderName
          $certifiFolderName=$stagingFolderName+"\\certifi"
          $sourceFolderName="staging\\"+$folderName+"\\*"
          Copy-Item -Path $sourceFolderName -Recurse -Destination C:\\Users\\runneradmin\\acmhome\\ -Verbose
          echo "About to dir C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\Users\\runneradmin\\acmhome\\
          dir 
      - shell: python
        name: Save secrets to file
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: |
          import base64, subprocess, sys, os, pathlib
          #Import first secrets file
          with open('C:\\Users\\runneradmin\\acmconfig\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECRET'])
          #Import second secrets file
          with open('C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECOND'])
      - name: Run setup on
        run: |
          $env:Path = "C:\\hostedtoolcache\\windows\\Python\\3.10.7\\x64\\Scripts\\;" + $env:Path
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo 'About to: acm setup on'
          acm setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-projects-arm.git
          echo "About to dir"
          dir
      - name: Run platform on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm platform on
      - name: Run platform off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm platform off
      - name: Setup Off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run setup off"
          acm setup off
          echo "About to dir"
          dir
      - name: Delete Secrets
        run: |
          del "C:\\Users\\runneradmin\\acmconfig\\keys.yaml"
          del 'C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml'
  e2e-tests-windows-cloudformation:
    needs: [release-a-windows-version]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureWindowsAgent
        uses: ./.github/actions/windows-provisioner
      - shell: pwsh
        name: Download and extract Release
        env:
          DESCRIPTION: ${{ inputs.description }}
          VERSION: ${{ inputs.version }}
          GH_TOKEN: ${{ secrets.HUSH }}
        run: |
          $vers="windows-"+$env:VERSION
          $repoWithToken = '"https://"+$env:GH_TOKEN+"@github.com/AgileCloudInstitute/AgileCloudManager"'
          echo "About to download release"
          gh release download $vers --archive zip --repo $repoWithToken
          $zipName="AgileCloudManager-"+$vers+".zip"
          mkdir staging
          Expand-Archive $zipName -DestinationPath "staging"
          $folderName="AgileCloudManager-"+$vers
          $stagingFolderName="staging\\"+$folderName
          $sourceFolderName="staging\\"+$folderName+"\\*"
          Copy-Item -Path $sourceFolderName -Recurse -Destination C:\\Users\\runneradmin\\acmhome\\ -Verbose
          echo "About to dir C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\Users\\runneradmin\\acmhome\\
          dir 
      - shell: python
        name: Save secrets to file
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: |
          import base64, subprocess, sys, os, pathlib
          #Import first secrets file
          with open('C:\\Users\\runneradmin\\acmconfig\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECRET'])
          #Import second secrets file
          with open('C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECOND'])
      - name: Run setup on
        run: |
          $env:Path = "C:\\hostedtoolcache\\windows\\Python\\3.10.7\\x64\\Scripts\\;" + $env:Path
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          python -m pip install --upgrade pip requests
          echo 'About to: acm setup on'
          acm setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-projects-cf.git
          echo "About to dir"
          dir
      - name: Run platform on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd 'C:\\stgng\\'
          echo ".................about to run e2e test"
          acm platform on
      - name: Run platform off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm platform off
      - name: Setup Off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run setup off"
          acm setup off
          echo "About to dir"
          dir
      - name: Delete Secrets
        run: |
          del C:\\Users\\runneradmin\\acmconfig\\keys.yaml
          del C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml
  e2e-tests-windows-custom:
    needs: [release-a-windows-version]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureWindowsAgent
        uses: ./.github/actions/windows-provisioner
      - shell: pwsh
        name: Download and extract Release
        env:
          DESCRIPTION: ${{ inputs.description }}
          VERSION: ${{ inputs.version }}
          GH_TOKEN: ${{ secrets.HUSH }}
        run: |
          $vers="windows-"+$env:VERSION
          $repoWithToken = '"https://"+$env:GH_TOKEN+"@github.com/AgileCloudInstitute/AgileCloudManager"'
          echo "About to download release"
          gh release download $vers --archive zip --repo $repoWithToken
          $zipName="AgileCloudManager-"+$vers+".zip"
          mkdir staging
          Expand-Archive $zipName -DestinationPath "staging"
          $folderName="AgileCloudManager-"+$vers
          $stagingFolderName="staging\\"+$folderName
          $sourceFolderName="staging\\"+$folderName+"\\*"
          Copy-Item -Path $sourceFolderName -Recurse -Destination C:\\Users\\runneradmin\\acmhome\\ -Verbose
          echo "About to dir C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\Users\\runneradmin\\acmhome\\
          dir 
      - shell: python
        name: Save secrets to file
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: |
          import base64, subprocess, sys, os, pathlib
          #Import first secrets file
          with open('C:\\Users\\runneradmin\\acmconfig\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECRET'])
          #Import second secrets file
          with open('C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECOND'])
      - name: Run setup on
        run: |
          $env:Path = "C:\\hostedtoolcache\\windows\\Python\\3.10.7\\x64\\Scripts\\;" + $env:Path
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          python -m pip install --upgrade pip requests
          echo 'About to: acm setup on'
          acm setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-custom.git
          echo "About to dir"
          dir
      - name: Run platform on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm platform on
      - name: Run platform off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm platform off
      - name: Setup Off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run setup off"
          acm setup off
          echo "About to dir"
          dir
      - name: Delete Secrets
        run: |
          del C:\\Users\\runneradmin\\acmconfig\\keys.yaml
          del C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml
  e2e-tests-windows-terraform-packer:
    needs: [release-a-windows-version]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: ConfigureWindowsAgent
        uses: ./.github/actions/windows-provisioner
      - shell: pwsh
        name: Download and extract Release
        env:
          DESCRIPTION: ${{ inputs.description }}
          VERSION: ${{ inputs.version }}
          GH_TOKEN: ${{ secrets.HUSH }}
        run: |
          $vers="windows-"+$env:VERSION
          $repoWithToken = '"https://"+$env:GH_TOKEN+"@github.com/AgileCloudInstitute/AgileCloudManager"'
          echo "About to download release"
          gh release download $vers --archive zip --repo $repoWithToken
          $zipName="AgileCloudManager-"+$vers+".zip"
          mkdir staging
          Expand-Archive $zipName -DestinationPath "staging"
          $folderName="AgileCloudManager-"+$vers
          $stagingFolderName="staging\\"+$folderName
          $sourceFolderName="staging\\"+$folderName+"\\*"
          Copy-Item -Path $sourceFolderName -Recurse -Destination C:\\Users\\runneradmin\\acmhome\\ -Verbose
          echo "About to dir C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\Users\\runneradmin\\acmhome\\
          dir 
      - shell: python
        name: Save secrets to file
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: |
          import base64, subprocess, sys, os, pathlib
          #Import first secrets file
          with open('C:\\Users\\runneradmin\\acmconfig\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECRET'])
          #Import second secrets file
          with open('C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml', 'w') as key_file:
            key_file.write(os.environ['ACM_SECOND'])
      - name: Run setup on
        run: |
          $env:Path = "C:\\hostedtoolcache\\windows\\Python\\3.10.7\\x64\\Scripts\\;" + $env:Path
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          python -m pip install --upgrade pip requests
          echo 'About to: acm setup on'
          acm setup on sourceRepo=https://github.com/AgileCloudInstitute/acm-config-terraform-packer.git
          echo "About to dir"
          dir
      - name: Run tfbackend serviceType on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm serviceType on systemName=tfbackend serviceType=tfBackend
      - name: Run tfbackend serviceType off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm serviceType off systemName=tfbackend serviceType=tfBackend
      - name: Run tfbackend serviceInstance on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm serviceInstance on systemName=tfbackend serviceType=tfBackend serviceInstance=adminAccounts
      - name: Run tfbackend serviceInstance off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm serviceInstance off systemName=tfbackend serviceType=tfBackend serviceInstance=adminAccounts
      - name: Run tfbackend services on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm services on systemName=tfbackend
      - name: Run admin foundation on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm foundation on systemName=admin
      - name: Run admin services on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm services on systemName=admin
      - name: Run agents foundation on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm foundation on systemName=agents
      - name: Run agents services on
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm services on systemName=agents
      - name: Run agents services off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm services off systemName=agents
      - name: Run agents foundation off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm foundation off systemName=agents
      - name: Run admin services off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm services off systemName=admin
      - name: Run admin foundation off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm foundation off systemName=admin
      - name: Run tfbackend services off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run e2e test"
          acm services off systemName=tfbackend
      - name: Setup Off
        run: |
          $env:Path += ";C:\\Users\\runneradmin\\acmhome\\"
          cd C:\\stgng\\
          echo ".................about to run setup off"
          acm setup off
          echo "About to dir"
          dir
      - name: Delete Secrets
        run: |
          del C:\\Users\\runneradmin\\acmconfig\\keys.yaml
          del C:\\Users\\runneradmin\\acm\\keys\\adminAccounts\\keys.yaml
