name: release-linux
on:
  push:
    branches:
      - release-linux
jobs:
  unit-tests-linux-misc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: First step
        shell: bash
        env:
          ACM_SECRET: ${{ secrets.ACM_REPO }}
          ACM_SECOND: ${{ secrets.ACM_REPO_SECOND }}
        run: | 
          echo "About to pwd"
          pwd
          echo "About to show contents of pwd"
          ls -al
