name: test-environ
on:
  push:
    branches:
      - test
jobs:
  1st-call-e2e-tests-workflow:
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  2nd-call-e2e-tests-workflow:
    needs: [1st-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  3rd-call-e2e-tests-workflow:
    needs: [1st-call-e2e-tests-workflow, 2nd-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  4th-call-e2e-tests-workflow:
    needs: [1st-call-e2e-tests-workflow, 2nd-call-e2e-tests-workflow, 3rd-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  5th-call-e2e-tests-workflow:
    needs: [1st-call-e2e-tests-workflow, 2nd-call-e2e-tests-workflow, 3rd-call-e2e-tests-workflow, 4th-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  6th-call-e2e-tests-workflow:
    needs: [1st-call-e2e-tests-workflow, 2nd-call-e2e-tests-workflow, 3rd-call-e2e-tests-workflow, 4th-call-e2e-tests-workflow, 5th-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  7th-call-e2e-tests-workflow:
    needs: [1st-call-e2e-tests-workflow, 2nd-call-e2e-tests-workflow, 3rd-call-e2e-tests-workflow, 4th-call-e2e-tests-workflow, 5th-call-e2e-tests-workflow, 6th-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  8th-call-e2e-tests-workflow:
    needs: [1st-call-e2e-tests-workflow, 2nd-call-e2e-tests-workflow, 3rd-call-e2e-tests-workflow, 4th-call-e2e-tests-workflow, 5th-call-e2e-tests-workflow, 6th-call-e2e-tests-workflow, 7th-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  9th-call-e2e-tests-workflow:
    needs: [1st-call-e2e-tests-workflow, 2nd-call-e2e-tests-workflow, 3rd-call-e2e-tests-workflow, 4th-call-e2e-tests-workflow, 5th-call-e2e-tests-workflow, 6th-call-e2e-tests-workflow, 7th-call-e2e-tests-workflow, 8th-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  10th-call-e2e-tests-workflow:
    needs: [1st-call-e2e-tests-workflow, 2nd-call-e2e-tests-workflow, 3rd-call-e2e-tests-workflow, 4th-call-e2e-tests-workflow, 5th-call-e2e-tests-workflow, 6th-call-e2e-tests-workflow, 7th-call-e2e-tests-workflow, 8th-call-e2e-tests-workflow, 9th-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit

