name: test-environ
on:
  push:
    branches:
      - test
jobs:
  first-call-e2e-tests-workflow:
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  second-call-e2e-tests-workflow:
    needs: [first-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  third-call-e2e-tests-workflow:
    needs: [first-call-e2e-tests-workflow, second-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  fourth-call-e2e-tests-workflow:
    needs: [first-call-e2e-tests-workflow, second-call-e2e-tests-workflow, third-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  fifth-call-e2e-tests-workflow:
    needs: [first-call-e2e-tests-workflow, second-call-e2e-tests-workflow, third-call-e2e-tests-workflow, fourth-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  sixth-call-e2e-tests-workflow:
    needs: [first-call-e2e-tests-workflow, second-call-e2e-tests-workflow, third-call-e2e-tests-workflow, fourth-call-e2e-tests-workflow, fifth-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  seventh-call-e2e-tests-workflow:
    needs: [first-call-e2e-tests-workflow, second-call-e2e-tests-workflow, third-call-e2e-tests-workflow, fourth-call-e2e-tests-workflow, fifth-call-e2e-tests-workflow, sixth-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  eigth-call-e2e-tests-workflow:
    needs: [first-call-e2e-tests-workflow, second-call-e2e-tests-workflow, third-call-e2e-tests-workflow, fourth-call-e2e-tests-workflow, fifth-call-e2e-tests-workflow, sixth-call-e2e-tests-workflow, seventh-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  ninth-call-e2e-tests-workflow:
    needs: [first-call-e2e-tests-workflow, second-call-e2e-tests-workflow, third-call-e2e-tests-workflow, fourth-call-e2e-tests-workflow, fifth-call-e2e-tests-workflow, sixth-call-e2e-tests-workflow, seventh-call-e2e-tests-workflow, eigth-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
  tenth-call-e2e-tests-workflow:
    needs: [first-call-e2e-tests-workflow, second-call-e2e-tests-workflow, third-call-e2e-tests-workflow, fourth-call-e2e-tests-workflow, fifth-call-e2e-tests-workflow, sixth-call-e2e-tests-workflow, seventh-call-e2e-tests-workflow, eigth-call-e2e-tests-workflow, ninth-call-e2e-tests-workflow]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
