name: Reusable workflow example
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        name: Do anything
        env:
          USERNAME: ${{ inputs.username }}
          TOKEN: ${{ secrets.token }}
        run: | 
          echo "username is $USERNAME"
          echo "token is: $TOKEN"
#      - uses: octo-org/my-action@v1
#        with:
#          username: ${{ inputs.username }}
#          token: ${{ secrets.token }}
#This workflow documentation here: https://docs.github.com/en/actions/using-workflows/reusing-workflows
